apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/part-of: k8s-incident-lab
spec:
  namespaceSelector:
    matchNames:
      - incident-lab
  selector:
    matchLabels:
      app.kubernetes.io/name: podinfo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
